# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'JrigToolsV2UI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(514, 563)
        Dialog.setWindowFlag(Qt.WindowMinimizeButtonHint, True)
        self.ChangeLW_Bt = QPushButton(Dialog)
        self.ChangeLW_Bt.setObjectName(u"ChangeLW_Bt")
        self.ChangeLW_Bt.setGeometry(QRect(220, 230, 101, 23))
        self.ConnectIKFKSwitchBT = QPushButton(Dialog)
        self.ConnectIKFKSwitchBT.setObjectName(u"ConnectIKFKSwitchBT")
        self.ConnectIKFKSwitchBT.setGeometry(QRect(10, 250, 161, 23))
        self.TfToWM_Bt = QPushButton(Dialog)
        self.TfToWM_Bt.setObjectName(u"TfToWM_Bt")
        self.TfToWM_Bt.setGeometry(QRect(10, 170, 161, 23))
        self.ConnectRT_Bt = QPushButton(Dialog)
        self.ConnectRT_Bt.setObjectName(u"ConnectRT_Bt")
        self.ConnectRT_Bt.setGeometry(QRect(10, 290, 161, 23))
        self.ConnectTF_Bt = QPushButton(Dialog)
        self.ConnectTF_Bt.setObjectName(u"ConnectTF_Bt")
        self.ConnectTF_Bt.setGeometry(QRect(10, 330, 161, 23))
        self.Connect_ScaleBt = QPushButton(Dialog)
        self.Connect_ScaleBt.setObjectName(u"Connect_ScaleBt")
        self.Connect_ScaleBt.setGeometry(QRect(10, 370, 161, 23))
        self.SearchFrom_LB = QLabel(Dialog)
        self.SearchFrom_LB.setObjectName(u"SearchFrom_LB")
        self.SearchFrom_LB.setGeometry(QRect(300, 160, 158, 36))
        self.Match_Ctrl_BT = QPushButton(Dialog)
        self.Match_Ctrl_BT.setObjectName(u"Match_Ctrl_BT")
        self.Match_Ctrl_BT.setGeometry(QRect(220, 190, 75, 23))
        self.Search_MatchCtrl_LE = QLineEdit(Dialog)
        self.Search_MatchCtrl_LE.setObjectName(u"Search_MatchCtrl_LE")
        self.Search_MatchCtrl_LE.setGeometry(QRect(300, 190, 156, 20))
        self.Px_LB = QLabel(Dialog)
        self.Px_LB.setObjectName(u"Px_LB")
        self.Px_LB.setGeometry(QRect(410, 220, 31, 36))
        self.LinewidthLE = QLineEdit(Dialog)
        self.LinewidthLE.setObjectName(u"LinewidthLE")
        self.LinewidthLE.setGeometry(QRect(330, 230, 61, 20))
        self.ResetLWC_Bt = QPushButton(Dialog)
        self.ResetLWC_Bt.setObjectName(u"ResetLWC_Bt")
        self.ResetLWC_Bt.setGeometry(QRect(220, 310, 171, 23))
        self.Renamer_Button = QPushButton(Dialog)
        self.Renamer_Button.setObjectName(u"Renamer_Button")
        self.Renamer_Button.setGeometry(QRect(10, 60, 61, 23))
        self.Name_LE = QLineEdit(Dialog)
        self.Name_LE.setObjectName(u"Name_LE")
        self.Name_LE.setGeometry(QRect(82, 60, 241, 20))
        self.Renamer_LB = QLabel(Dialog)
        self.Renamer_LB.setObjectName(u"Renamer_LB")
        self.Renamer_LB.setGeometry(QRect(10, 10, 81, 16))
        font = QFont()
        font.setPointSize(14)
        self.Renamer_LB.setFont(font)
        self.RigToolsLB = QLabel(Dialog)
        self.RigToolsLB.setObjectName(u"RigToolsLB")
        self.RigToolsLB.setGeometry(QRect(30, 130, 91, 31))
        self.RigToolsLB.setFont(font)
        self.Ctrl_Tools_Lb = QLabel(Dialog)
        self.Ctrl_Tools_Lb.setObjectName(u"Ctrl_Tools_Lb")
        self.Ctrl_Tools_Lb.setGeometry(QRect(270, 130, 141, 31))
        self.Ctrl_Tools_Lb.setFont(font)
        self.MergeCurve_Bt = QPushButton(Dialog)
        self.MergeCurve_Bt.setObjectName(u"MergeCurve_Bt")
        self.MergeCurve_Bt.setGeometry(QRect(220, 350, 75, 23))
        self.ObjToJnt_Bt = QPushButton(Dialog)
        self.ObjToJnt_Bt.setObjectName(u"ObjToJnt_Bt")
        self.ObjToJnt_Bt.setGeometry(QRect(10, 210, 161, 23))
        self.AutoPosfix_CB = QCheckBox(Dialog)
        self.AutoPosfix_CB.setObjectName(u"AutoPosfix_CB")
        self.AutoPosfix_CB.setGeometry(QRect(80, 90, 121, 17))
        self.ObjectOnground = QPushButton(Dialog)
        self.ObjectOnground.setObjectName(u"ObjectOnground")
        self.ObjectOnground.setGeometry(QRect(20, 520, 111, 23))
        self.ObjectToCenterScene_Bt = QPushButton(Dialog)
        self.ObjectToCenterScene_Bt.setObjectName(u"ObjectToCenterScene_Bt")
        self.ObjectToCenterScene_Bt.setGeometry(QRect(150, 520, 141, 23))
        self.Utility_Lb = QLabel(Dialog)
        self.Utility_Lb.setObjectName(u"Utility_Lb")
        self.Utility_Lb.setGeometry(QRect(20, 480, 111, 31))
        self.Utility_Lb.setFont(font)
        self.MatchCtrlJointOrient_CB = QComboBox(Dialog)
        self.MatchCtrlJointOrient_CB.addItem("")
        self.MatchCtrlJointOrient_CB.addItem("")
        self.MatchCtrlJointOrient_CB.addItem("")
        self.MatchCtrlJointOrient_CB.setObjectName(u"MatchCtrlJointOrient_CB")
        self.MatchCtrlJointOrient_CB.setGeometry(QRect(460, 190, 41, 22))
        self.ColorPattlet_Bt = QPushButton(Dialog)
        self.ColorPattlet_Bt.setObjectName(u"ColorPattlet_Bt")
        self.ColorPattlet_Bt.setGeometry(QRect(260, 270, 61, 23))
        self.Color_LB = QLabel(Dialog)
        self.Color_LB.setObjectName(u"Color_LB")
        self.Color_LB.setGeometry(QRect(220, 270, 51, 21))
        self.ImportSwitchCtrl_BT = QPushButton(Dialog)
        self.ImportSwitchCtrl_BT.setObjectName(u"ImportSwitchCtrl_BT")
        self.ImportSwitchCtrl_BT.setGeometry(QRect(20, 450, 71, 23))
        self.ImportCtrl_LB = QLabel(Dialog)
        self.ImportCtrl_LB.setObjectName(u"ImportCtrl_LB")
        self.ImportCtrl_LB.setGeometry(QRect(20, 410, 171, 31))
        self.ImportCtrl_LB.setFont(font)
        self.ImportFKCtrl_BT = QPushButton(Dialog)
        self.ImportFKCtrl_BT.setObjectName(u"ImportFKCtrl_BT")
        self.ImportFKCtrl_BT.setGeometry(QRect(100, 450, 51, 23))
        self.ImportIK_BT = QPushButton(Dialog)
        self.ImportIK_BT.setObjectName(u"ImportIK_BT")
        self.ImportIK_BT.setGeometry(QRect(160, 450, 51, 23))
        self.MatchWithSearch_CB = QCheckBox(Dialog)
        self.MatchWithSearch_CB.setObjectName(u"MatchWithSearch_CB")
        self.MatchWithSearch_CB.setGeometry(QRect(190, 420, 121, 17))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("JrigToolsV2", u"JrigToolsV2", None))
        self.ChangeLW_Bt.setText(QCoreApplication.translate("Dialog", u"Change line Width", None))
        self.ConnectIKFKSwitchBT.setText(QCoreApplication.translate("Dialog", u"Create IK_FK_System", None))
        self.TfToWM_Bt.setText(QCoreApplication.translate("Dialog", u"Transfrom To World Matrix", None))
        self.ConnectRT_Bt.setText(QCoreApplication.translate("Dialog", u"Connect Rotate", None))
        self.ConnectTF_Bt.setText(QCoreApplication.translate("Dialog", u"Connect Transfrom", None))
        self.Connect_ScaleBt.setText(QCoreApplication.translate("Dialog", u"Connect Scale", None))
        self.SearchFrom_LB.setText(QCoreApplication.translate("Dialog", u"Search From", None))
        self.Match_Ctrl_BT.setText(QCoreApplication.translate("Dialog", u"Match Ctrl", None))
        self.Px_LB.setText(QCoreApplication.translate("Dialog", u"px", None))
        self.ResetLWC_Bt.setText(QCoreApplication.translate("Dialog", u"Reset line Width And Color", None))
        self.Renamer_Button.setText(QCoreApplication.translate("Dialog", u"Rename", None))
        self.Renamer_LB.setText(QCoreApplication.translate("Dialog", u"Renamer", None))
        self.RigToolsLB.setText(QCoreApplication.translate("Dialog", u"Rig_Tools", None))
        self.Ctrl_Tools_Lb.setText(QCoreApplication.translate("Dialog", u"Controller_Tools", None))
        self.MergeCurve_Bt.setText(QCoreApplication.translate("Dialog", u"Merge Curve", None))
        self.ObjToJnt_Bt.setText(QCoreApplication.translate("Dialog", u"Object To Joint", None))
        self.AutoPosfix_CB.setText(QCoreApplication.translate("Dialog", u"Auto Posfix By Type", None))
        self.ObjectOnground.setText(QCoreApplication.translate("Dialog", u"Object On Ground", None))
        self.ObjectToCenterScene_Bt.setText(QCoreApplication.translate("Dialog", u"Object To Center Scene", None))
        self.Utility_Lb.setText(QCoreApplication.translate("Dialog", u"Utility_Tools", None))
        self.MatchCtrlJointOrient_CB.setItemText(0, QCoreApplication.translate("Dialog", u"X", None))
        self.MatchCtrlJointOrient_CB.setItemText(1, QCoreApplication.translate("Dialog", u"Y", None))
        self.MatchCtrlJointOrient_CB.setItemText(2, QCoreApplication.translate("Dialog", u"Z", None))

        self.ColorPattlet_Bt.setText("")
        self.Color_LB.setText(QCoreApplication.translate("Dialog", u"Color", None))
        self.ImportSwitchCtrl_BT.setText(QCoreApplication.translate("Dialog", u"Switch", None))
        self.ImportCtrl_LB.setText(QCoreApplication.translate("Dialog", u"Import Controller", None))
        self.ImportFKCtrl_BT.setText(QCoreApplication.translate("Dialog", u"FK", None))
        self.ImportIK_BT.setText(QCoreApplication.translate("Dialog", u"IK", None))
        self.MatchWithSearch_CB.setText(QCoreApplication.translate("Dialog", u"Match With Search", None))
    # retranslateUi

